/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************/

#include <stdint.h>
#include "main.h"

#include "fpu.h"
#include "uart.h"
#include "neo6m_driver.h"
#include "neo6m_buffer.h"
#include "nmea_parser_lib.h"

extern gps_data_t _gps_data;



int main(void)
{
	fpu_enable();
	debug_uart_init();

	neo6m_uart_init();
	neo6m_buffer_init();

	ublox_disable_all_nmea();
	ublox_enable_nmea_sentence(GGA);
	ublox_enable_nmea_sentence(RMC);


    while(1)
    {
    	gps_nmea_update();

    }

}
